### PR TITLE
Fixed intallation scripts and removed default region from variables.tf

### PR DESCRIPTION
**Pull request by lusoal**
### What does this PR do?

🛑 Please open an issue first to discuss any significant work and flesh out details/direction - we would hate for your time to be wasted.
Consult the [CONTRIBUTING](https://github.com/awslabs/data-on-eks/blob/main/CONTRIBUTING.md#contributing-via-pull-requests) guide for submitting pull-requests.

Users needs to make sure that variables.tf is updated according to their needs before deploying through install.sh.

### Motivation

I was executing the hands-on labs to join area of focus and noticed that the resources were being created in us-west-2 region, so the variable was not being overlapped 

### More

- [X] Yes, I have tested the PR using my local account setup (Provide any test evidence report under Additional Notes)
- [ ] Mandatory for new blueprints. Yes, I have added a example to support my blueprint PR
- [ ] Mandatory for new blueprints. Yes, I have updated the `website/docs` or `website/blog` section for this feature
- [X] Yes, I ran `pre-commit run -a` with this PR. Link for installing [pre-commit](https://pre-commit.com/) locally

### For Moderators

- [ ] E2E Test successfully complete before merge?

### Additional Notes

I also fixed Kafka doc on website, since it is related to this PR

### CODE REVIEW

**Review by vara-bonthu — APPROVED** [review]
LGTM 👍🏼 Thanks for the PR @lusoal 🚀

**Comment by vara-bonthu** [comment]
@lusoal Could you please resolve the conflicts. We are good to merge once its updated

**Comment by raykrueger** [comment]
The cleanup scripts now ask for the region twice :)

**Comment by lusoal** [comment]
> The cleanup scripts now ask for the region twice :)

It is because the region var is not defined on vars.tf, in the cleanup script it is required to pass the value typed by the user to:

```bash
terraform destroy -target="$target" -var="region=$AWS_DEFAULT_REGION" -auto-approve
```

**Comment by vara-bonthu** [comment]
@lusoal  default region should be defined in the `variables.tf` file to ensure Github workflows are working. 

I think it's better that we remove the read region in `install.sh` and `cleanup.sh` scripts from all blueprints. By default it should use `us-west-2` as defined in `variables.tf` file. Users needs to update this file if they want to run in different region.

I have done this change in recent PR for this blueprint `analytics/terraform/emr-eks-karpenter/install.sh`

**Comment by lusoal** [comment]
> @lusoal default region should be defined in the `variables.tf` file to ensure Github workflows are working.
> 
> I think it's better that we remove the read region in `install.sh` and `cleanup.sh` scripts from all blueprints. By default it should use `us-west-2` as defined in `variables.tf` file. Users needs to update this file if they want to run in different region.
> 
> I have done this change in recent PR for this blueprint `analytics/terraform/emr-eks-karpenter/install.sh`

Agree on that Vara, we just need to explicitly say that on the instructions, or define a AWS_DEFAULT_REGION on GitHub actions when triggering the workflow

**Pull request merged**
