### PR TITLE
docs: Improve Superset on EKS doc

### PR DESCRIPTION
**Pull request by sguruvar**
### What does this PR do?

🛑 Please open an issue first to discuss any significant work and flesh out details/direction - we would hate for your time to be wasted.
Consult the [CONTRIBUTING](https://github.com/awslabs/data-on-eks/blob/main/CONTRIBUTING.md#contributing-via-pull-requests) guide for submitting pull-requests.

### Motivation

superset on EKS changes
### More

- [X] Yes, I have tested the PR using my local account setup (Provide any test evidence report under Additional Notes)
- [X] Mandatory for new blueprints. Yes, I have added a example to support my blueprint PR
- [X] Mandatory for new blueprints. Yes, I have updated the `website/docs` or `website/blog` section for this feature
- [X] Yes, I ran `pre-commit run -a` with this PR. Link for installing [pre-commit](https://pre-commit.com/) locally

### For Moderators

- [ ] E2E Test successfully complete before merge?

### CODE REVIEW

**Review by askulkarni2 — COMMENTED** [review]
@sguruvar thanks for the PR! Please fix the codespell errors. Also, in future, please run `pre-commit run -a` in your local workstation to avoid these kinds of errors.

**Comment by vara-bonthu** [comment]
@sguruvar Checkout the spelling suggestions and update the PR.

**Comment by sguruvar** [comment]
> @sguruvar thanks for the PR! Please fix the codespell errors. Also, in future, please run `pre-commit run -a` in your local workstation to avoid these kinds of errors.

Fixed the codespell errors

**Comment by sguruvar** [comment]
> @sguruvar Checkout the spelling suggestions and update the PR.

done

**Comment by askulkarni2** [comment]
> > @sguruvar thanks for the PR! Please fix the codespell errors. Also, in future, please run `pre-commit run -a` in your local workstation to avoid these kinds of errors.
> 
> 
> 
> Fixed the codespell errors

Still seeing some pre-commit errors.

**Comment by vara-bonthu** [comment]
Looks like  pre-commit issues are related to Spark Streaming PR. This looks good to me.

**Review by vara-bonthu — APPROVED** [review]
LGTM

**Pull request merged**
